import Head from 'next/head';
import Navigation from '../../Nagivation/Navigation';
import peopleJson from '../../libs/people';
import styles from '../../styles/Home.module.css';
import { useRouter } from 'next/router';

export default function Person({
  about,
  address,
  age,
  balance,
  company,
  email,
  eyeColor,
  gender,
  name,
}) {
  const router = useRouter();
  const handleOnClick = (guid) => {
    router.push(`/Detail/${guid}`);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>People</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navigation />
        <h1>{name}</h1>
        <div>
          <h3>About {name}:</h3>
          <p>{about}</p>
          <ul>
            <li>Gender: {gender}</li>
            <li>Eye Color: {eyeColor}</li>
            <li>Age: {age}</li>
            <li>Address: {address}</li>
            <li>Company: {company} </li>
            <li>Cash monay: {balance}</li>
            <li>Email: {email}</li>
          </ul>
        </div>
        <h3>Check out other people:</h3>
        <div>
        {peopleJson.map(({guid, name}) => {
            return (
              <li key={guid} onClick={() => handleOnClick(guid)}>
                {name}
              </li>
            )
            })}
        </div>
        <div style={{height: '20px'}}></div>
        <a href="http://localhost:3000">Go Back home</a>
      </main>
    </div>
  );
}

export async function getStaticPaths() {
  const paths = peopleJson.map((person) => {
    return {
      params: {
        guid: person.guid,
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const foundPerson = peopleJson.find((person) => person.guid === params.guid);
  return {
    props: foundPerson,
  };
}
