import Head from 'next/head';
import Navigation from '../../Nagivation/Navigation';
import React from 'react';
import peopleJson from '../../libs/people';
import { useRouter } from 'next/router';

export default function Person({guid}) {
  const router = useRouter();
  const handleOnClick = (guid) => {
    router.push(`/Detail/${guid}`);
  };
  return (
    <div>
      <Head>
        <title>People</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navigation />
        <h1>Detail</h1>

        <div>
          {peopleJson.map(({ guid, name }) => {
            return (
              <li key={guid} onClick={() => handleOnClick(guid)}>
                {name}
              </li>
            );
          })}
        </div>
      </main>
    </div>
  );
}
