import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Navigation from '../Nagivation/Navigation';
import React from 'react';

function Admin() {
  const { data: session } = useSession();
  if (session) {
    return (
      <div>
        <Head>
          <title>People</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
          <Navigation />
          <h1>Congratulations on being an admin, you can see this page...</h1>
          <p>...nothing to see here..</p>
        </main>
      </div>
    );
  } else {
    return (
      <div>
        <Head>
          <title>People</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
          <Navigation />
          <h1>You need to be admin to see this page</h1>
        </main>
      </div>
    );
  }
}

export default Admin;
