import * as Yup from 'yup';

import { Field, Form, Formik } from 'formik';

import Head from 'next/head';
import Navigation from '../Nagivation/Navigation';
import React from 'react';

function Contact() {
  const SignupSchema = Yup.object().shape({
    firstName: Yup.string()
      .min(3, 'First name needs to be at least 3 characters')
      .max(50, 'First name cannot be longer than 50 characters')
      .required('Required'),
    lastName: Yup.string()
      .min(4, 'Last name needs to be at least 4 characters')
      .max(50, 'Last name cannot be longer than 50 characters')
      .required('Required'),
    email: Yup.string().email('Invalid email').required('Required'),
    subject: Yup.string().required('Required'),
    message: Yup.string()
      .min(10, 'Message needs to be at least 10 characters')
      .max(150, 'Message cannot be longer than 150 characters'),
  });

  return (
    <div>
      <Head>
        <title>People</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>
          <Navigation />
        </div>

        <h1>Contact</h1>
        
        <Formik
          initialValues={{
            firstName: '',
            lastName: '',
            email: '',
            message: '',
          }}
          validationSchema={SignupSchema}
          onSubmit={(values) => {
            console.log(values);
          }}
        >
          {({ errors, touched }) => (
            <Form>
              <p>Name:</p>
              <Field
                name='firstName'
              />
              {errors.firstName && touched.firstName ? (
                <div>{errors.firstName}</div>
              ) : null}
              <p>Last Name:</p>
              <Field
                name='lastName'
              />
              {errors.lastName && touched.lastName ? (
                <div>{errors.lastName}</div>
              ) : null}
              <p>Email:</p>
              <Field
                name='email'
                type='email'
              />
              {errors.email && touched.email ? <div>{errors.email}</div> : null}
              <p>Subject:</p>
              <Field
                name='subject'
                as='select'
              >
                <option value=''></option>
                <option value='Products'>Products</option>
                <option value='Shipping'>Shipping</option>
                <option value='Jobs'>Jobs</option>
                <option value='Help'>Help</option>
              </Field>
              {errors.subject || touched.subject ? (
                <div>{errors.subject}</div>
              ) : null}
              <p>Message:</p>
              <Field
                name='message'
                as='textarea'
                placeholder='Write your message here'
              ></Field>
              {errors.message && touched.message ? (
                <div>{errors.message}</div>
              ) : null}

              <button
                type='submit'
              >
                Submit
              </button>
            </Form>
          )}
        </Formik>
      </main>
    </div>
  );
}

export default Contact;
