const peopleJson = [
  {
    _id: "623ad5b70404e19b41755d0d",
    index: 0,
    guid: "86a8a038-11df-4315-9d20-1d9f299a1007",
    isActive: false,
    balance: "$2,575.90",
    picture: "http://placehold.it/32x32",
    age: 31,
    eyeColor: "green",
    name: "Sandy Ford",
    gender: "female",
    company: "BIZMATIC",
    email: "sandyford@bizmatic.com",
    phone: "+1 (999) 462-3572",
    address: "413 Adelphi Street, Efland, American Samoa, 8187",
    about:
      "Et irure tempor eiusmod esse dolore qui. Voluptate velit ullamco in eiusmod eu ipsum veniam velit laborum amet ullamco sint velit. Dolore do in ipsum sint eiusmod nulla ex. Dolor fugiat cupidatat anim excepteur incididunt eu eu amet ipsum est. Reprehenderit sit elit do pariatur consectetur.\r\n",
  },
  {
    _id: "623ad5b7a6af407f8e37b6dd",
    index: 1,
    guid: "af938be4-133b-4f0d-9032-b1a9976623a4",
    isActive: false,
    balance: "$1,741.41",
    picture: "http://placehold.it/32x32",
    age: 37,
    eyeColor: "blue",
    name: "Cabrera Beck",
    gender: "male",
    company: "EMTRAK",
    email: "cabrerabeck@emtrak.com",
    phone: "+1 (979) 459-3815",
    address: "116 Chapel Street, Fairhaven, Puerto Rico, 5044",
    about:
      "Sint qui anim ad culpa Lorem id esse Lorem deserunt labore. Nostrud est laboris sunt sunt. Ex pariatur aute pariatur excepteur nisi. Qui eiusmod proident duis occaecat qui cillum incididunt officia non consequat ex. Tempor duis aute esse mollit aute dolor cupidatat esse dolor sint do. Elit aliquip Lorem officia occaecat ut exercitation esse laborum aliqua esse esse et. Occaecat nulla ipsum id commodo officia labore.\r\n",
  },
  {
    _id: "623ad5b79e4585cc10075321",
    index: 2,
    guid: "793305e3-5aac-4b5d-9181-d6ce14f5034d",
    isActive: true,
    balance: "$3,838.23",
    picture: "http://placehold.it/32x32",
    age: 31,
    eyeColor: "blue",
    name: "Ora Dawson",
    gender: "female",
    company: "VERAQ",
    email: "oradawson@veraq.com",
    phone: "+1 (974) 422-2123",
    address: "709 Jamison Lane, Elliston, Rhode Island, 9675",
    about:
      "Laborum ullamco laborum ut consequat veniam reprehenderit minim aliquip duis deserunt tempor. Nostrud officia amet aliqua esse sint sint enim deserunt ex duis dolore enim. Enim ipsum deserunt veniam nostrud nostrud commodo in. Eu aliquip do reprehenderit non.\r\n",
  },
  {
    _id: "623ad5b74f3b127eed568f9e",
    index: 3,
    guid: "2fc85f26-c3bb-40bd-ac78-b1dad3561fae",
    isActive: false,
    balance: "$1,936.30",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "blue",
    name: "Hamilton Bean",
    gender: "male",
    company: "GLOBOIL",
    email: "hamiltonbean@globoil.com",
    phone: "+1 (897) 560-3142",
    address: "677 Mermaid Avenue, Brutus, West Virginia, 9646",
    about:
      "Id aliqua magna dolore et ad aliquip consequat elit esse amet. Aliquip minim eiusmod et enim proident dolore sit id. Sit ut incididunt sit enim ut ea non occaecat tempor quis Lorem commodo. Sunt id eiusmod enim tempor irure do consequat minim do aliquip id laboris ad.\r\n",
  },
  {
    _id: "623ad5b7501b59b952a306a1",
    index: 4,
    guid: "44883d24-63cf-4b95-ab68-ee4d5cf1d1c5",
    isActive: true,
    balance: "$1,273.97",
    picture: "http://placehold.it/32x32",
    age: 27,
    eyeColor: "brown",
    name: "Workman Patel",
    gender: "male",
    company: "MIRACULA",
    email: "workmanpatel@miracula.com",
    phone: "+1 (997) 485-3327",
    address: "801 Denton Place, Joes, Maine, 5496",
    about:
      "Officia proident aute nisi ea non voluptate voluptate aliqua aute. Eu id Lorem et duis pariatur magna culpa cupidatat aute. Occaecat pariatur amet sit reprehenderit est esse laborum reprehenderit consectetur qui laborum. Laborum dolore nulla culpa consectetur commodo ex adipisicing aliqua ad quis consectetur sunt. Aute elit nostrud eu sit dolor incididunt enim pariatur esse laborum. Ut excepteur esse magna ex reprehenderit commodo sunt mollit sunt occaecat enim. Irure reprehenderit consequat occaecat voluptate velit est nisi tempor excepteur amet esse ad.\r\n",
  },
  {
    _id: "623ad5b73e24f7ff6e6859a7",
    index: 5,
    guid: "dd132b8e-89d4-4d38-b8e5-2454ced335b3",
    isActive: false,
    balance: "$3,558.58",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "green",
    name: "Richards Wade",
    gender: "male",
    company: "ZYTREX",
    email: "richardswade@zytrex.com",
    phone: "+1 (984) 483-2017",
    address: "728 Sumner Place, Coaldale, Minnesota, 9484",
    about:
      "Dolor exercitation Lorem fugiat sint incididunt est eu incididunt culpa cillum. Non incididunt minim deserunt eu aliquip in sit excepteur tempor dolor. Fugiat aliqua ut commodo nulla. Voluptate culpa amet aliqua aliquip culpa reprehenderit adipisicing incididunt labore eu officia nostrud. Exercitation aute fugiat non id duis officia duis proident. Reprehenderit sit adipisicing aliquip consequat exercitation laboris voluptate nulla pariatur.\r\n",
  },
  {
    _id: "623ad5b783f74d08a5e63871",
    index: 6,
    guid: "9bac04da-8b07-48bf-9702-c808be908776",
    isActive: true,
    balance: "$1,095.91",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "blue",
    name: "Swanson Quinn",
    gender: "male",
    company: "SIGNITY",
    email: "swansonquinn@signity.com",
    phone: "+1 (824) 501-2682",
    address: "766 Karweg Place, Fedora, Kansas, 9966",
    about:
      "Esse consectetur ex veniam aute. Sint dolore minim laboris nulla qui nulla ut ea irure incididunt aliquip ad. Occaecat pariatur eiusmod culpa labore. Non veniam velit laborum esse anim fugiat in veniam duis quis in commodo dolore laboris. Laboris ipsum ullamco cupidatat nulla ex nisi. Culpa duis dolor dolor et magna. Ex quis dolor enim ipsum ipsum ut ipsum duis esse sint voluptate do consequat enim.\r\n",
  },
];

export default peopleJson;
